package turbocabs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author milin
 */
public class carInfo extends javax.swing.JFrame {
    
            spCInfo cdet=new spCInfo(); 

    /**
     * Creates new form carInfo
     */
    public carInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clabtn = new javax.swing.JButton();
        x1btn = new javax.swing.JButton();
        beetlebtn = new javax.swing.JButton();
        mcbtn = new javax.swing.JButton();
        bsedbtn = new javax.swing.JButton();
        a4btn = new javax.swing.JButton();
        innbtn = new javax.swing.JButton();
        q7btn = new javax.swing.JButton();
        exbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Cars Index");

        jLabel1.setText("Micro");

        jLabel2.setText("Mini");

        jLabel3.setText("Sedan");

        jLabel4.setText("SUV");

        clabtn.setText("Mercedes CLA");
        clabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clabtnActionPerformed(evt);
            }
        });

        x1btn.setText("BMW X1");
        x1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1btnActionPerformed(evt);
            }
        });

        beetlebtn.setText("Volkswagen Beetle");
        beetlebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beetlebtnActionPerformed(evt);
            }
        });

        mcbtn.setText("Mini Cooper");
        mcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcbtnActionPerformed(evt);
            }
        });

        bsedbtn.setText("BMW 330i");
        bsedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsedbtnActionPerformed(evt);
            }
        });

        a4btn.setText("Audi A4");
        a4btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4btnActionPerformed(evt);
            }
        });

        innbtn.setText("Toyota Innova");
        innbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                innbtnActionPerformed(evt);
            }
        });

        q7btn.setText("Audi Q7");
        q7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7btnActionPerformed(evt);
            }
        });

        exbtn.setText("Cancel");
        exbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("(This will redirect you to the main page and you will have to enter your info again)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(innbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bsedbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(beetlebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(clabtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(x1btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mcbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(a4btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(q7btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(x1btn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mcbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beetlebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a4btn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsedbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(innbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(q7btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clabtnActionPerformed
        // TODO add your handling code here:
     try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con1 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st1=con1.createStatement();
           ResultSet rs1=st1.executeQuery("select * from infocar where Model='CLA' ");
         
             while(rs1.next()){
             String model=rs1.getString("Model");
             
             String name=rs1.getString("Name");
             
             String type=rs1.getString("Type");
             
             String num=rs1.getString("CNumber");
             
             String rate=rs1.getString("Rate");
             
             
             
            
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
              this.setVisible(false);
              this.dispose();
     }
         
         }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
            
    }//GEN-LAST:event_clabtnActionPerformed

    private void x1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con2 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st2=con2.createStatement();
           ResultSet rs2=st2.executeQuery("select * from infocar where Model='X1' ");

           while(rs2.next()){
             String model=rs2.getString("Model");
             
             String name=rs2.getString("Name");
             
             String type=rs2.getString("Type");
             
             String num=rs2.getString("CNumber");
             
             String rate=rs2.getString("Rate");
             
             
                 
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_x1btnActionPerformed

    private void innbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_innbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con3 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st3=con3.createStatement();
           ResultSet rs3=st3.executeQuery("select * from infocar where Model='Innova' ");

           while(rs3.next()){
             String model=rs3.getString("Model");
             
             String name=rs3.getString("Name");
             
             String type=rs3.getString("Type");
             
             String num=rs3.getString("CNumber");
             
             String rate=rs3.getString("Rate");
             
             
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_innbtnActionPerformed

    private void beetlebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beetlebtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con4 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st4=con4.createStatement();
           ResultSet rs4=st4.executeQuery("select * from infocar where Model='Beetle' ");

           while(rs4.next()){
             String model=rs4.getString("Model");
             
             String name=rs4.getString("Name");
             
             String type=rs4.getString("Type");
             
             String num=rs4.getString("CNumber");
             
             String rate=rs4.getString("Rate");
             
             
            
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_beetlebtnActionPerformed

    private void mcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con5 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st5=con5.createStatement();
           ResultSet rs5=st5.executeQuery("select * from infocar where Model='Cooper' ");

           while(rs5.next()){
             String model=rs5.getString("Model");
             
             String name=rs5.getString("Name");
             
             String type=rs5.getString("Type");
             
             String num=rs5.getString("CNumber");
             
             String rate=rs5.getString("Rate");
             
             
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_mcbtnActionPerformed

    private void bsedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsedbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con6 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st6=con6.createStatement();
           ResultSet rs6=st6.executeQuery("select * from infocar where Model='330i' ");

           while(rs6.next()){
             String model=rs6.getString("Model");
             
             String name=rs6.getString("Name");
             
             String type=rs6.getString("Type");
             
             String num=rs6.getString("CNumber");
             
             String rate=rs6.getString("Rate");
             
             
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_bsedbtnActionPerformed

    private void a4btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con7 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st7=con7.createStatement();
           ResultSet rs7=st7.executeQuery("select * from infocar where Model='A4' ");

           while(rs7.next()){
             String model=rs7.getString("Model");
             
             String name=rs7.getString("Name");
             
             String type=rs7.getString("Type");
             
             String num=rs7.getString("CNumber");
             
             String rate=rs7.getString("Rate");
             
             
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_a4btnActionPerformed

    private void q7btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7btnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con8 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st8=con8.createStatement();
           ResultSet rs8=st8.executeQuery("select * from infocar where Model='Q7' ");

           while(rs8.next()){
             String model=rs8.getString("Model");
             
             String name=rs8.getString("Name");
             
             String type=rs8.getString("Type");
             
             String num=rs8.getString("CNumber");
             
             String rate=rs8.getString("Rate");
             
             
             
              cdet.cmodel.setText(model);
              cdet.cname.setText(name);
              cdet.ctype.setText(type);
              cdet.cnumber.setText(num);
              cdet.crate.setText(rate);
              cdet.setVisible(true);
              
             
           
        }
           
        }
        catch (ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(this,"Connection Failed");
        }
    }//GEN-LAST:event_q7btnActionPerformed

    private void exbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exbtnActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/mydb1", "root", "B@rca4ever");
           Statement st1=conn.createStatement();
           String qrdr="select * from bname where id=1 ";
           String qrdr1="delete from bname where id=1 ";
           ResultSet rst=st1.executeQuery(qrdr);
           while(rst.next())
           {
               String nm=rst.getString("name");
               String qrdr2="delete from tempinfo where UName='"+nm+"' ";
               PreparedStatement stmt4=conn.prepareStatement(qrdr2);
                stmt4.execute();
               PreparedStatement stmt=conn.prepareStatement(qrdr1);
                stmt.execute();
           }
             
             this.setVisible(false);
             this.dispose();
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, "Connection Failed");
        }
    }//GEN-LAST:event_exbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new carInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a4btn;
    private javax.swing.JButton beetlebtn;
    private javax.swing.JButton bsedbtn;
    private javax.swing.JButton clabtn;
    private javax.swing.JButton exbtn;
    private javax.swing.JButton innbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mcbtn;
    private javax.swing.JButton q7btn;
    private javax.swing.JButton x1btn;
    // End of variables declaration//GEN-END:variables
}
